import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { CollectorCoverage, SNAPSHOT_FACET_NAMES, SnapshotFacetName } from '../../../contracts/snapshot.js';
import { SnapAcquisitionRequest } from './snap-selection.js';
export type CollectorPhase = 'baseline' | 'mutating';
export interface DeclaredArtifact { readonly key: string; readonly path: string; readonly media_type: string; readonly retained_arrays?: readonly { readonly key: string; readonly json_pointer: string; readonly retained_count: number }[]; }
export interface NamedCoverage { readonly name: string; readonly coverage: CollectorCoverage; }
export interface SnapshotCollectorContext { readonly request: SnapAcquisitionRequest; readonly root: string; write(artifact: DeclaredArtifact, bytes: Uint8Array): void; restore(name: string, restore: () => Promise<{ readonly restored: boolean; readonly reason?: string }>): void; }
export interface CollectorResult<N extends SnapshotFacetName> { readonly primary: NamedCoverage; readonly subpopulations: Record<string, CollectorCoverage>; readonly artifacts: readonly DeclaredArtifact[]; }
export interface RegisteredSnapshotCollector<N extends SnapshotFacetName = SnapshotFacetName> { readonly facet: N; readonly phase: CollectorPhase; readonly requested: (request: SnapAcquisitionRequest) => boolean; readonly collect: (ctx: SnapshotCollectorContext) => Promise<CollectorResult<N>>; }
export class SnapshotCollectorRegistry { constructor(readonly entries: readonly RegisteredSnapshotCollector[]) {} }
export function defineSnapshotCollectors(entries: readonly RegisteredSnapshotCollector[]): SnapshotCollectorRegistry { const seen = new Set(entries.map(entry => entry.facet)); if (entries.length !== SNAPSHOT_FACET_NAMES.length || seen.size !== entries.length || SNAPSHOT_FACET_NAMES.some(facet => !seen.has(facet)) || entries.some(entry => entry.phase !== 'baseline' && entry.phase !== 'mutating')) throw new Error('snapshot collector registration must contain each fixed facet exactly once'); return new SnapshotCollectorRegistry([...entries].sort((a, b) => SNAPSHOT_FACET_NAMES.indexOf(a.facet) - SNAPSHOT_FACET_NAMES.indexOf(b.facet))); }
const unavailable = (reason: string): CollectorCoverage => ({ retained_count: 0, availability: { state: 'unavailable', reason }, truncation: { state: 'unknown' }, source_total: { state: 'unavailable', reason } });
/** U7 replaces registrations, not orchestration. Placeholder collectors intentionally acquire no browser evidence. */
const placeholderSubpopulations = (facet: SnapshotFacetName): Record<string, CollectorCoverage> => facet === 'queries' ? { 'media-queries': unavailable('collector-unavailable'), 'container-queries': unavailable('collector-unavailable') } : facet === 'focus' ? { forward: unavailable('collector-unavailable'), reverse: unavailable('collector-unavailable') } : facet === 'scroll' ? { 'snap-descendants': unavailable('collector-unavailable'), 'sticky-fixed-descendants': unavailable('collector-unavailable'), 'sampled-visible-children': unavailable('collector-unavailable') } : {};
export const defaultSnapshotCollectors = defineSnapshotCollectors(SNAPSHOT_FACET_NAMES.map(facet => ({ facet, phase: 'baseline' as const, requested: request => facet !== 'pixels' || request.pixels ? facet !== 'states' || request.states.length > 0 : false, collect: async () => ({ primary: { name: facet, coverage: unavailable('collector-unavailable') }, subpopulations: placeholderSubpopulations(facet), artifacts: [] }) })));
export function createArtifactWriter(root: string, restorers: Array<{ name: string; restore: () => Promise<{ restored: boolean; reason?: string }> }>): Pick<SnapshotCollectorContext, 'write' | 'restore'> { const paths = new Set<string>(); return { write(artifact, bytes) { if (!artifact.path || path.isAbsolute(artifact.path) || artifact.path.includes('\\') || artifact.path.split('/').some(item => !item || item === '.' || item === '..') || paths.has(artifact.path)) throw new Error('invalid or duplicate collector artifact path'); paths.add(artifact.path); const output = path.join(root, artifact.path); fs.mkdirSync(path.dirname(output), { recursive: true, mode: 0o700 }); fs.writeFileSync(output, bytes); }, restore(name, restore) { restorers.push({ name, restore }); } }; }
export function sourceArtifactDeclaration(root: string, artifact: DeclaredArtifact) { const data = fs.readFileSync(path.join(root, artifact.path)); return { key: artifact.key, path: artifact.path, bytes: data.length, sha256: crypto.createHash('sha256').update(data).digest('hex'), media_type: artifact.media_type, retained_arrays: artifact.retained_arrays ?? [] }; }
