/**
 * LinkedIn Library
 *
 * Browser-executable LinkedIn operations via Voyager API.
 * Requires user to be logged into LinkedIn.
 */

// Types from schemas - single source of truth
export type {
  Profile,
  FullProfile,
  SearchResult,
  Company,
  Post,
  Reactor,
  Comment,
  Conversation,
  Message,
  GetContextOutput,
  GetMeOutput,
  GetProfileByVanityNameOutput,
  GetFullProfileOutput,
  GetContactInfoOutput,
  GetProfileBadgesOutput,
  SearchPeopleOutput,
  SearchCompaniesOutput,
  ListConnectionsOutput,
  GetMemberRelationshipOutput,
  SendConnectionRequestOutput,
  WithdrawConnectionRequestOutput,
  GetInvitationsSummaryOutput,
  ListConnectionRequestsOutput,
  ListInvitationsOutput,
  GetCompanyOutput,
  GetCompanyFollowingStateOutput,
  GetCompanyPostsOutput,
  GetHomeFeedOutput,
  GetPostsOutput,
  GetProfileCommentsOutput,
  GetProfileReactionsOutput,
  GetPostReactionsOutput,
  GetPostCommentsOutput,
  LikePostOutput,
  UnlikePostOutput,
  CreateCommentOutput,
  EditCommentOutput,
  DeleteCommentOutput,
  LikeCommentOutput,
  UnlikeCommentOutput,
  ListConversationsOutput,
  ViewConversationOutput,
  GetConversationWithUserOutput,
  SendMessageOutput,
  CreateGroupChatOutput,
  RenameGroupChatOutput,
  GetComposeOptionsOutput,
  EditMessageOutput,
  DeleteMessageOutput,
  ReactToMessageOutput,
  UnreactToMessageOutput,
  CreatePostOutput,
  DeletePostOutput,
  RepostPostOutput,
  SchedulePostOutput,
  ListScheduledPostsOutput,
  ScheduledPost,
  SearchPostsOutput,
  GetProfileViewsSummaryOutput,
  GetSocialSellingIndexOutput,
  ListProfileViewersOutput,
  SearchJobsOutput,
  ListNotificationsOutput,
  RemoveConnectionOutput,
  ResolveGeoOutput,
  ResolveIndustryOutput,
  ResolveSchoolOutput,
  ResolveCompanyIdOutput,
  // Sales Navigator types
  SearchLeadsOutput,
  SearchAccountsOutput,
  GetLeadProfileOutput,
  GetLeadTimelineOutput,
  GetAccountDetailOutput,
  GetAccountLeadsOutput,
  ListLeadListsOutput,
  ListAccountListsOutput,
  GetLeadsInListOutput,
  CreateListOutput,
  DeleteListOutput,
  SaveLeadOutput,
  UnsaveLeadOutput,
  GetLeadNotesOutput,
  CreateNoteOutput,
  UpdateNoteOutput,
  DeleteNoteOutput,
  ListInMailThreadsOutput,
  ViewInMailThreadOutput,
  SendInMailOutput,
  ListSavedSearchesOutput,
  ListSalesNavNotificationsOutput,
  GetInMailCreditsOutput,
  SearchFilterValuesOutput,
  GetAccountDossierOutput,
  GetAccountHeadcountOutput,
  GetLeadHighlightsOutput,
  LeadResult,
  AccountResult,
  // Recruiter (Talent Solutions) types
  GetRecruiterContextOutput,
  ListContractsOutput,
  ListSeatsOutput,
  ListHiringProjectsOutput,
  GetHiringProjectOutput,
  SearchCandidatesOutput,
  ListCandidateRecommendationsOutput,
  FindSimilarProfilesOutput,
  SearchProfilesByKeywordOutput,
  RecruiterTypeaheadOutput,
  GetSearchFacetsOutput,
  GetCandidateProfileOutput,
  GetProjectCandidateOutput,
  GetCandidatesInProjectOutput,
  GetCandidateActivityOutput,
  GetProfileResumeUrlOutput,
  GetMailboxSummaryOutput,
  GetMailboxMetadataOutput,
  GetRecruiterConversationOutput,
  GetCandidateMessagesOutput,
  ListSourcingChannelsOutput,
  ListRecruiterNotificationsOutput,
  ListRecruiterTagsOutput,
  LogProfileViewOutput,
} from './schemas';

// Context operations
export { getContext } from './context';
export type { LinkedInContext } from './context';

// Profile operations
export {
  getMe,
  getProfileByVanityName,
  getFullProfile,
  getContactInfo,
  getProfileBadges,
  downloadProfilePicture,
} from './profiles';

// Search operations
export {
  searchPeople,
  searchCompanies,
  searchPosts,
  searchJobs,
  resolveGeo,
  resolveIndustry,
  resolveSchool,
  resolveCompanyId,
} from './search';

// Connection operations
export {
  listConnections,
  getMemberRelationship,
  sendConnectionRequest,
  listSentConnectionRequests,
  withdrawConnectionRequest,
  getInvitationsSummary,
  listConnectionRequests,
  listInvitations,
  handleInvitationAction,
  removeConnection,
} from './connections';

// Company operations
export {
  getCompany,
  getCompanyFollowingState,
  updateFollowingState,
  getCompanyPosts,
  listAdminCompanies,
  getAvailableActors,
} from './companies';

// Messaging operations
export {
  listConversations,
  viewConversation,
  getConversationWithUser,
  sendMessage,
  createGroupChat,
  renameGroupChat,
  getComposeOptions,
  editMessage,
  deleteMessage,
  reactToMessage,
  unreactToMessage,
  markAllConversationsAsRead,
  markConversationAsRead,
  downloadAttachment,
} from './messaging';

// Post interaction operations
export {
  likePost,
  unlikePost,
  createPost,
  deletePost,
  editPost,
  repostPost,
  undoRepost,
  createComment,
  editComment,
  deleteComment,
  getPosts,
  getHomeFeed,
  getProfileComments,
  getProfileReactions,
  getPostReactions,
  getCommentReactions,
  getPostComments,
  likeComment,
  unlikeComment,
  schedulePost,
  listScheduledPosts,
  editScheduledPost,
  reschedulePost,
} from './posts';

// Notifications operations
export { listNotifications, getNotificationCounts } from './notifications';

// Analytics operations
export {
  getProfileViewsSummary,
  getSocialSellingIndex,
  listProfileViewers,
  getCreatorAnalyticsSummary,
  getContentAnalytics,
  getAudienceDemographics,
  getCompanyPageAnalytics,
  listCompanyPageViewers,
} from './analytics';

// Sales Navigator operations (requires Sales Navigator tier)
export {
  searchLeads,
  searchAccounts,
  getLeadProfile,
  getLeadTimeline,
  getAccountDetail,
  getAccountLeads,
  listLeadLists,
  listAccountLists,
  getLeadsInList,
  createList,
  deleteList,
  updateList,
  getAccountsInList,
  saveLead,
  unsaveLead,
  addLeadToList,
  removeLeadFromList,
  addAccountToList,
  removeAccountFromList,
  saveAccount,
  unsaveAccount,
  getLeadNotes,
  getAccountNotes,
  createNote,
  updateNote,
  deleteNote,
  listInMailThreads,
  viewInMailThread,
  sendInMail,
  listSavedSearches,
  listSalesNavNotifications,
  getInMailCredits,
  searchFilterValues,
  getAccountDossier,
  getAccountHeadcount,
  getLeadHighlights,
} from './sales-nav';

// Recruiter (Talent Solutions) operations (requires a LinkedIn Recruiter seat)
export {
  getRecruiterContext,
  listContracts,
  listSeats,
  listHiringProjects,
  getHiringProject,
  searchCandidates,
  listCandidateRecommendations,
  findSimilarProfiles,
  searchProfilesByKeyword,
  typeahead,
  getSearchFacets,
  getCandidateProfile,
  getProjectCandidate,
  getCandidatesInProject,
  getCandidateActivity,
  getProfileResumeUrl,
  getMailboxSummary,
  getMailboxMetadata,
  getConversation,
  getCandidateMessages,
  listSourcingChannels,
  listRecruiterNotifications,
  listRecruiterTags,
  logProfileView,
} from './recruiter';
