import { z } from 'zod';

// ============================================================================
// Shared Parameters
// ============================================================================

const AccessTokenParam = z
  .string()
  .describe('Bearer access token from getContext()');

const WorkspaceIdParam = z
  .string()
  .describe('Workspace UUID from getContext()');

const AssistantIdParam = z
  .string()
  .describe('Assistant UUID from listAssistants()');

// ============================================================================
// Entity Schemas
// ============================================================================

export const ThreadSchema = z.object({
  id: z.string().describe('Thread UUID'),
  title: z.string().optional().describe('Thread title (auto-generated by AI)'),
  createdAt: z.string().describe('ISO timestamp when created'),
  updatedAt: z.string().describe('ISO timestamp when last updated'),
  creator: z
    .object({
      id: z.string().describe('Creator user UUID'),
      type: z.string().describe('Creator type (native_user)'),
    })
    .optional()
    .describe('Thread creator info'),
});

export const MessagePartSchema = z.object({
  id: z.string().describe('Part UUID'),
  type: z
    .string()
    .describe('Part type: text, html, tool, image, file, thinkingText'),
  content: z
    .record(z.string(), z.unknown())
    .optional()
    .describe(
      'Part content. For text: {text}. For html: {html, json}. Absent for tool parts.',
    ),
  status: z.string().optional().describe('Part status (present on tool parts)'),
  sourceObjects: z
    .array(z.unknown())
    .optional()
    .describe('Source objects referenced in this part (html parts)'),
  // Tool-part fields (type === "tool"): top-level, NOT inside content
  name: z.string().optional().describe('Tool name (for tool parts)'),
  llmId: z
    .string()
    .optional()
    .describe('LLM tool call ID from the AI provider (for tool parts)'),
  input: z
    .record(z.string(), z.unknown())
    .optional()
    .describe('Tool call input arguments (for tool parts)'),
  output: z
    .record(z.string(), z.unknown())
    .optional()
    .describe('Tool call result/output (for tool parts)'),
});

export const ThreadMessageSchema = z.object({
  id: z.string().describe('Message UUID'),
  createdAt: z.string().describe('ISO timestamp when created'),
  updatedAt: z.string().describe('ISO timestamp when last updated'),
  status: z.string().describe('Message status: completed, streaming, error'),
  statusVersion: z
    .number()
    .optional()
    .describe('Internal version counter for status updates'),
  source: z
    .string()
    .optional()
    .describe('Message source: manual (user) or assistant'),
  modelId: z
    .string()
    .optional()
    .describe('AI model used (for assistant messages)'),
  parts: z
    .array(MessagePartSchema)
    .describe('Message content parts (text, tool calls, etc.)'),
  creator: z.object({
    id: z.string(),
    type: z.string().describe('native_user or native_assistant'),
  }),
  focusObjects: z
    .array(
      z.object({
        id: z
          .string()
          .describe(
            'Object ID: email for contacts, domain for orgs, UUID for others',
          ),
        type: z
          .string()
          .describe('Object type (e.g., native_contact, native_opportunity)'),
      }),
    )
    .optional()
    .describe(
      'CRM objects in focus when this user message was sent (only present on user messages sent with focusObjects)',
    ),
  compactedSummary: z
    .object({
      task: z.string().describe('Summary of what the assistant did'),
      decisions: z.array(z.string()).describe('Key decisions made'),
      constraints: z.array(z.string()).describe('Constraints encountered'),
      errors: z.array(z.string()).describe('Errors encountered'),
      referencedObjects: z
        .array(
          z.object({
            objectType: z.string(),
            objectId: z.string(),
            summary: z.string(),
            updatedAt: z.string().optional(),
          }),
        )
        .describe('CRM objects referenced in this message'),
    })
    .optional()
    .describe(
      'AI-generated summary of assistant messages (present on compacted long threads)',
    ),
});

export const ThreadDetailSchema = z.object({
  id: z.string().describe('Thread UUID'),
  title: z.string().optional().describe('Thread title'),
  workspaceId: z.string(),
  status: z.string().describe('Thread status: idle, streaming, error'),
  statusVersion: z
    .number()
    .optional()
    .describe('Internal version counter for status updates'),
  modelId: z.string().optional().describe('AI model ID'),
  assistantId: z.string().optional().describe('Assistant UUID'),
  messages: z.array(ThreadMessageSchema).describe('All messages in the thread'),
  sourceObject: z
    .object({ id: z.string(), type: z.string() })
    .optional()
    .describe('Source object this thread is about'),
  objectReferences: z
    .array(z.unknown())
    .optional()
    .describe('CRM objects referenced in this thread'),
  exists: z.unknown().optional().describe('Internal existence marker'),
});

export const SearchResultItemSchema = z.object({
  label: z.string().describe('Display name'),
  description: z.string().optional().describe('Short description'),
  photoUrl: z.string().nullable().optional().describe('Photo/logo URL'),
  objectId: z.string().describe('Object ID (email, domain, or UUID)'),
  updatedAt: z.string().describe('ISO timestamp'),
});

export const AssistantScheduleSchema = z.object({
  id: z.string().describe('Schedule UUID'),
  name: z.string().describe('Schedule display name'),
  enabled: z.boolean().describe('Whether schedule is active'),
  scheduleType: z
    .string()
    .describe(
      'Schedule type: DAILY_AM (morning), DAILY_PM (evening), WEEKLY, EVERY_4_HOURS (6x/day, requires Enterprise tier)',
    ),
  timeOfDay: z
    .string()
    .optional()
    .describe('Time in HH:MM format (e.g., "09:00")'),
  timezone: z.string().describe('Timezone (e.g., "America/Los_Angeles")'),
  prompt: z.string().describe('Instructions for the scheduled task'),
  instructions: z
    .string()
    .nullable()
    .optional()
    .describe(
      'Optional additional context for the schedule, separate from the main prompt',
    ),
  preferredModel: z
    .string()
    .nullable()
    .optional()
    .describe('AI model override'),
  preferredTemperature: z
    .number()
    .nullable()
    .optional()
    .describe('Temperature override (0-1)'),
  notificationTarget: z
    .string()
    .nullable()
    .optional()
    .describe('Notification destination'),
  templateIds: z
    .array(z.string())
    .optional()
    .describe(
      'Skill template IDs attached to this schedule (e.g., "briefing", "todo", "pipelineanalysis"). Always an empty array when no templates are attached; never null.',
    ),
  assistantId: z
    .string()
    .optional()
    .describe('UUID of the parent assistant that owns this schedule'),
  createdAt: z
    .string()
    .optional()
    .describe('ISO timestamp when schedule was created'),
  updatedAt: z
    .string()
    .optional()
    .describe('ISO timestamp when schedule was last updated'),
  lastRunAt: z
    .string()
    .nullable()
    .optional()
    .describe(
      'ISO timestamp of the most recent schedule execution, null if never run',
    ),
  nextRunAt: z
    .string()
    .nullable()
    .optional()
    .describe('ISO timestamp of the next scheduled execution'),
  lastRunStatus: z
    .string()
    .nullable()
    .optional()
    .describe('Status of the most recent run (null if never run)'),
  goalId: z
    .string()
    .nullable()
    .optional()
    .describe(
      'UUID of the AssistantGoal linked to this schedule, or null if not linked to a goal',
    ),
  runCount: z
    .number()
    .optional()
    .describe(
      'Total number of times this schedule has been executed. 0 if never run.',
    ),
});

export const AssistantToolInstructionSchema = z.object({
  id: z.string().describe('Tool instruction UUID'),
  toolId: z.string().describe('Tool identifier this instruction applies to'),
  instructions: z.string().describe('Custom instructions for this tool'),
});

export const AssistantEventInstructionSchema = z.object({
  id: z.string().describe('Event instruction UUID'),
  instructions: z.string().describe('Custom instructions for this event type'),
  eventId: z
    .enum(['CHAT', 'MEETING_RECORDING_READY_FOR_OWNER'])
    .describe(
      'Event type: CHAT (chat interactions), MEETING_RECORDING_READY_FOR_OWNER (meeting recording processed)',
    ),
});

export const AssistantSchema = z.object({
  id: z.string().describe('Assistant UUID'),
  workspaceId: z.string(),
  firstName: z.string().describe('Assistant first name'),
  lastName: z.string().describe('Assistant last name'),
  description: z.string().optional().describe('Assistant description'),
  title: z.string().nullable().optional().describe('Assistant title'),
  ownerId: z.string().describe('Owner user UUID'),
  tierId: z.string().describe('Tier UUID'),
  photoUrl: z.string().optional().describe('Avatar URL'),
  schedules: z
    .array(AssistantScheduleSchema)
    .describe('Configured schedules for this assistant'),
  tier: z
    .object({
      id: z.string(),
      name: z
        .string()
        .describe('Tier name: Free, Turbo, Professional, Executive'),
      schedules: z
        .array(z.string())
        .describe('Allowed schedule types for this tier'),
    })
    .optional(),
  instructions: z
    .array(AssistantToolInstructionSchema)
    .nullable()
    .optional()
    .describe(
      'Tool-specific instructions overriding default behavior for individual tools',
    ),
  eventInstructions: z
    .array(AssistantEventInstructionSchema)
    .optional()
    .describe(
      'Event-specific instructions: custom behavior for CHAT interactions or MEETING_RECORDING_READY_FOR_OWNER events',
    ),
});

export const WorkspaceMemberSchema = z.object({
  id: z.string().describe('Member user UUID'),
  email: z.string().describe('Member email address'),
  status: z.string().describe('Member status: ACTIVE, INVITED, etc.'),
  roleId: z.string().describe('Role UUID'),
  isDefaultOwner: z.boolean().optional(),
  invitedAt: z
    .string()
    .nullable()
    .optional()
    .describe(
      'ISO timestamp when the member was invited (null for workspace creator)',
    ),
  invitedBy: z
    .string()
    .nullable()
    .optional()
    .describe(
      'Email or ID of the user who sent the invite (null for workspace creator)',
    ),
  coreContact: z
    .object({
      firstName: z.string().nullable().optional(),
      lastName: z.string().nullable().optional(),
      email: z
        .string()
        .nullable()
        .optional()
        .describe('Member email from contact record'),
      photo: z.string().nullable().optional().describe('Profile photo URL'),
      title: z.string().nullable().optional(),
      description: z
        .string()
        .nullable()
        .optional()
        .describe('Member bio/description'),
      linkedInUrl: z
        .string()
        .nullable()
        .optional()
        .describe('LinkedIn profile URL'),
      timezone: z.string().nullable().optional(),
      travelTimezone: z
        .string()
        .nullable()
        .optional()
        .describe('Travel timezone override'),
      domain: z
        .string()
        .nullable()
        .optional()
        .describe("Member's company domain"),
      twitterUrl: z
        .string()
        .nullable()
        .optional()
        .describe('Twitter/X profile URL'),
      facebookUrl: z
        .string()
        .nullable()
        .optional()
        .describe('Facebook profile URL'),
      githubUrl: z
        .string()
        .nullable()
        .optional()
        .describe('GitHub profile URL'),
    })
    .optional()
    .describe('Contact info for this member'),
});

export const WorkspaceSchema = z.object({
  id: z.string().describe('Workspace UUID'),
  name: z.string().describe('Workspace display name'),
  status: z.string().describe('Workspace status: ACTIVE, etc.'),
  setupStatus: z.string().describe('Setup completion status: COMPLETE, etc.'),
  createdByUserId: z.string().describe('Workspace creator user UUID'),
  creatorEmail: z
    .string()
    .optional()
    .describe('Email address of the workspace creator'),
  isDefault: z
    .boolean()
    .optional()
    .describe('Whether this is the default workspace for the user'),
  domains: z
    .array(
      z.object({
        domain: z.string(),
        autoInvite: z.boolean().optional(),
        autoInviteRoleId: z.string().optional(),
      }),
    )
    .describe('Claimed domains for this workspace'),
  members: z.array(WorkspaceMemberSchema).describe('Workspace members'),
  roles: z
    .array(
      z.object({
        id: z.string(),
        name: z.string().describe('Role name: Owner, Admin, Member'),
        description: z.string(),
        permissions: z
          .array(
            z.object({
              type: z
                .string()
                .describe(
                  'Permission category: OBJECT_TYPE, USERS, SETTINGS, BILLING',
                ),
              permission: z
                .string()
                .describe('Permission level: fullAccess, manage'),
              scope: z
                .string()
                .nullable()
                .optional()
                .describe('Scope (* = all object types, null = global)'),
            }),
          )
          .optional()
          .describe('Granular permission grants for this role'),
      }),
    )
    .describe('Available workspace roles'),
});

// ============================================================================
// Focus Object Schema
// ============================================================================

export const FocusObjectSchema = z.object({
  id: z
    .string()
    .describe(
      'Object primary ID: email for contacts, domain for organizations, UUID for opportunities/pages/actions/recordings/files',
    ),
  type: z
    .enum([
      'native_contact',
      'native_organization',
      'native_opportunity',
      'native_page',
      'native_action',
      'native_meetingrecording',
      'native_thread',
      'native_draft',
      'native_file',
    ])
    .describe(
      'CRM object type. Use native_file for uploaded file attachments (objectId from createFileObject). NOTE: the server does not validate this field; invalid values are silently forwarded. Use only the documented enum values.',
    ),
  filename: z
    .string()
    .optional()
    .describe(
      'Original filename; required when type is native_file. Passed as-is to the AI for context about the attached file.',
    ),
});

// ============================================================================
// Function Schemas
// ============================================================================

export const listThreadsSchema = {
  name: 'listThreads',
  description:
    'List all chat threads in the workspace. Returns threads with ID, title, and timestamps. Use getThread to retrieve full message history for a specific thread.',
  notes: '',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
  }),
  output: z.object({
    threads: z.array(ThreadSchema).describe('List of chat threads'),
  }),
};

export const getThreadSchema = {
  name: 'getThread',
  description:
    'Get full details of a chat thread including all messages, tool calls, and AI responses. Use this to read the conversation history.',
  notes: '',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
    threadId: z.string().describe('Thread UUID to retrieve'),
  }),
  output: z.object({
    thread: ThreadDetailSchema,
  }),
};

export const sendChatMessageSchema = {
  name: 'sendChatMessage',
  description:
    'Send a message to an AI assistant thread. Creates a new thread if threadId is not provided. Returns the threadId immediately; use getThread to retrieve the AI response once the thread status is idle.',
  notes:
    'The AI processes messages asynchronously. After calling this, poll getThread until thread.status === "idle" to read the response. Timezone defaults to America/Los_Angeles.',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
    message: z
      .string()
      .min(1)
      .describe('The message text to send; must be non-empty'),
    threadId: z
      .string()
      .optional()
      .describe(
        'Existing thread UUID. If omitted, a new thread is created automatically. WARNING: passing a non-existent UUID is silently accepted by the send API but will break the polling workflow; getThread will throw for a thread that does not exist. Always use a threadId returned from a previous sendChatMessage call or from listThreads.',
      ),
    assistantId: z
      .string()
      .optional()
      .describe(
        'Assistant UUID to use when creating a new thread. If omitted, uses the first assistant.',
      ),
    timezone: z
      .string()
      .optional()
      .default('America/Los_Angeles')
      .describe('IANA timezone string (e.g., "America/New_York")'),
    thinkingEnabled: z
      .boolean()
      .optional()
      .default(false)
      .describe(
        'Enable extended thinking mode (slower, deeper reasoning). Corresponds to "Thinking mode" in the UI. Default false = fast mode.',
      ),
    memoryEnabled: z
      .boolean()
      .optional()
      .default(false)
      .describe(
        'Enable assistant memory for this message. When true, the assistant saves important information across conversations. Stored per-workspace in the UI via localStorage key "memory-enabled:v1:{workspaceId}". Default false.',
      ),
    focusObjects: z
      .array(FocusObjectSchema)
      .optional()
      .default([])
      .describe(
        'CRM objects to focus the message on (provides context to the AI). When sending from a contact/org/opportunity page, pass the relevant object here. Shape: [{id: "email@example.com", type: "native_contact"}].',
      ),
    retryMessageId: z
      .string()
      .optional()
      .describe(
        'UUID of a failed assistant message to retry. When provided, the AI regenerates the response for that specific message. Corresponds to the "Retry" button shown on failed messages in the UI.',
      ),
    userMessageId: z
      .string()
      .nullable()
      .optional()
      .describe(
        'Client-generated UUID for the user message being sent. The UI always sends this field (null for new messages). Allows idempotent message creation; if provided, the server uses this as the message ID. Pass null or omit to let the server assign an ID.',
      ),
  }),
  output: z.object({
    threadId: z.string().describe('Thread UUID where the message was sent'),
    status: z
      .string()
      .describe('Always "sent"; poll getThread for AI response'),
  }),
};

export const searchWorkspaceSchema = {
  name: 'searchWorkspace',
  description:
    'Returns recently updated entities across the workspace: contacts, organizations, opportunities, pages, recordings, actions, pipelines. Use this to get an overview of recent activity or to browse what exists in the workspace.',
  notes:
    'Returns up to 10 results per entity type, ordered by most recently updated. This endpoint does not support keyword filtering; it always returns the most recently updated items regardless of any query.',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
  }),
  output: z.object({
    contacts: z.array(SearchResultItemSchema).describe('Matching contacts'),
    organizations: z
      .array(SearchResultItemSchema)
      .describe('Matching organizations'),
    opportunities: z
      .array(SearchResultItemSchema)
      .describe('Matching opportunities'),
    pages: z.array(SearchResultItemSchema).describe('Matching pages'),
    pipelines: z.array(SearchResultItemSchema).describe('Matching pipelines'),
    recordings: z
      .array(SearchResultItemSchema)
      .describe('Matching meeting recordings'),
    actions: z.array(SearchResultItemSchema).describe('Matching actions'),
  }),
};

export const getWorkspaceSchema = {
  name: 'getWorkspace',
  description:
    'Get workspace configuration including name, status, claimed domains, members, and roles.',
  notes: 'Requires the authenticated user email from getContext().',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
    email: z.string().describe('Authenticated user email from getContext()'),
  }),
  output: z.object({
    workspace: WorkspaceSchema,
  }),
};

export const listWorkspaceMembersSchema = {
  name: 'listWorkspaceMembers',
  description:
    'List all members of the workspace with their email, status, and role.',
  notes:
    'Both workspaceId and email are optional and auto-derived from the auth token if omitted or empty. ' +
    'email must match the authenticated user session; if it does not match, the server returns an opaque "Something went wrong" error. ' +
    'Omit email to have it derived automatically from the stored auth token.',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
    email: z
      .string()
      .optional()
      .describe(
        'Authenticated user email from getContext(). Must match the authenticated session; passing a different email causes a server error. Omit to derive automatically from the auth token.',
      ),
  }),
  output: z.object({
    members: z.array(WorkspaceMemberSchema).describe('Workspace members'),
  }),
};

export const listAssistantsSchema = {
  name: 'listAssistants',
  description:
    'List all AI assistants configured in the workspace. Each assistant has a name, personality, tier, and schedules.',
  notes: '',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
  }),
  output: z.object({
    assistants: z.array(AssistantSchema).describe('Configured AI assistants'),
  }),
};

export const listSchedulesSchema = {
  name: 'listSchedules',
  description:
    'List all scheduled tasks for an AI assistant. Schedules run automatically at configured times (daily AM, daily PM, or weekly).',
  notes: '',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
    assistantId: AssistantIdParam,
  }),
  output: z.object({
    schedules: z
      .array(AssistantScheduleSchema)
      .describe('Configured schedules'),
  }),
};

export const ScheduleInputSchema = z.object({
  name: z
    .string()
    .min(
      1,
      'Schedule name cannot be empty; the API accepts empty strings but creates an unusable schedule with no display name',
    )
    .describe('Schedule display name'),
  timezone: z
    .string()
    .describe('IANA timezone string (e.g., "America/Los_Angeles")'),
  prompt: z
    .string()
    .optional()
    .describe(
      'Instructions for the scheduled task. Required when creating; omitting causes a server error. Optional for updates (omitted = keep existing value).',
    ),
  scheduleType: z
    .enum(['DAILY_AM', 'DAILY_PM', 'WEEKLY', 'EVERY_4_HOURS'])
    .optional()
    .describe(
      'Schedule type: DAILY_AM (morning), DAILY_PM (evening), WEEKLY (Monday), EVERY_4_HOURS (6x/day, requires Enterprise tier)',
    ),
  timeOfDay: z
    .string()
    .optional()
    .describe(
      'Run time in HH:MM format (e.g., "09:00"). Required when creating a schedule; omitting it causes a server error. Optional for updates (omitted = keep existing value).',
    ),
  enabled: z.boolean().optional().describe('Whether schedule is active'),
  preferredModel: z.string().optional().describe('AI model override'),
  preferredTemperature: z
    .number()
    .optional()
    .describe(
      'AI temperature override (0–1). Controls response creativity. Note: once set, this field cannot be cleared back to null via updateSchedule; it can only be changed to a different number.',
    ),
  notificationTarget: z
    .string()
    .nullable()
    .optional()
    .describe(
      'Notification destination. Format: null (AI auto-decides), "email" (email only), "slack" (Slack DM only), "email+slack" (email + Slack DM), "slack : channelId1,channelId2" (specific Slack channels), "email+slack : channelId1,channelId2" (email + specific channels), "slack : all_internal" (all internal Slack channels). Use "__dm" as a channel token to include Slack DM alongside channels (e.g., "slack : __dm,channelId").',
    ),
  templateIds: z
    .array(z.string())
    .optional()
    .describe(
      'Skill template IDs to attach to this schedule. Known values: "briefing", "todo", "pipelineanalysis", "crmadmin". Templates provide pre-built prompts for common tasks.',
    ),
  instructions: z
    .string()
    .optional()
    .describe(
      'Additional context for the schedule, separate from the main prompt',
    ),
  goalId: z
    .string()
    .nullable()
    .optional()
    .describe(
      'UUID of an AssistantGoal to link this schedule to. Links the schedule to a specific goal in the assistant system. Use null to unlink.',
    ),
});

export const createScheduleSchema = {
  name: 'createSchedule',
  description:
    'Create a new scheduled task for an AI assistant. The schedule will run automatically at the specified time and send results to the configured notification target.',
  notes:
    'Allowed schedule types depend on the assistant tier; EVERY_4_HOURS requires Enterprise tier. Professional and Executive tiers support DAILY_AM, DAILY_PM, and WEEKLY. prompt and timeOfDay are required for creation; omitting either causes the API to return a generic "Something went wrong" error. Each scheduleType can only be used once per assistant; creating a duplicate type also returns a generic "Something went wrong" error. All server-side validation errors return the same opaque message; there is no way to distinguish between them programmatically.',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
    assistantId: AssistantIdParam,
    schedule: ScheduleInputSchema,
  }),
  output: z.object({
    schedule: AssistantScheduleSchema,
  }),
};

export const UpdateScheduleInputSchema = ScheduleInputSchema.extend({
  name: z
    .string()
    .min(
      1,
      'Schedule name cannot be empty; the API accepts empty strings but creates an unusable schedule with no display name',
    )
    .optional()
    .describe('Schedule display name. Omit to keep the existing name.'),
  timezone: z
    .string()
    .optional()
    .describe(
      'IANA timezone string (e.g., "America/Los_Angeles"). Omit to keep the existing timezone.',
    ),
});

export const updateScheduleSchema = {
  name: 'updateSchedule',
  description:
    'Update a scheduled task configuration (prompt, time, timezone, enabled status).',
  notes:
    'All fields are optional; only provided fields are updated. Omitted fields retain their current values. The function fetches the existing schedule and merges before sending. ' +
    'EVERY_4_HOURS requires Enterprise tier; if the workspace tier does not support it, the API returns a generic "Something went wrong" error that is indistinguishable from passing an entirely invalid value. Use DAILY_AM, DAILY_PM, or WEEKLY for non-Enterprise workspaces.',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
    scheduleId: z.string().describe('Schedule UUID to update'),
    schedule: UpdateScheduleInputSchema,
  }),
  output: z.object({
    schedule: AssistantScheduleSchema,
  }),
};

export const deleteScheduleSchema = {
  name: 'deleteSchedule',
  description: 'Delete a scheduled task from an AI assistant.',
  notes: '',
  input: z.object({
    accessToken: AccessTokenParam,
    workspaceId: WorkspaceIdParam,
    scheduleId: z.string().describe('Schedule UUID to delete'),
  }),
  output: z.object({
    deletedScheduleId: z.string().describe('UUID of the deleted schedule'),
  }),
};

// ============================================================================
// Type Exports
// ============================================================================

export type FocusObject = z.infer<typeof FocusObjectSchema>;
export type Thread = z.infer<typeof ThreadSchema>;
export type ThreadDetail = z.infer<typeof ThreadDetailSchema>;
export type ThreadMessage = z.infer<typeof ThreadMessageSchema>;
export type AssistantSchedule = z.infer<typeof AssistantScheduleSchema>;
export type AssistantToolInstruction = z.infer<
  typeof AssistantToolInstructionSchema
>;
export type AssistantEventInstruction = z.infer<
  typeof AssistantEventInstructionSchema
>;
export type Assistant = z.infer<typeof AssistantSchema>;
export type WorkspaceMember = z.infer<typeof WorkspaceMemberSchema>;
export type Workspace = z.infer<typeof WorkspaceSchema>;
export type SearchResultItem = z.infer<typeof SearchResultItemSchema>;
export type ScheduleInput = z.infer<typeof ScheduleInputSchema>;

export type ListThreadsInput = z.infer<typeof listThreadsSchema.input>;
export type ListThreadsOutput = z.infer<typeof listThreadsSchema.output>;
export type GetThreadInput = z.infer<typeof getThreadSchema.input>;
export type GetThreadOutput = z.infer<typeof getThreadSchema.output>;
export type SendChatMessageInput = z.infer<typeof sendChatMessageSchema.input>;
export type SendChatMessageOutput = z.infer<
  typeof sendChatMessageSchema.output
>;
export type SearchWorkspaceInput = z.infer<typeof searchWorkspaceSchema.input>;
export type SearchWorkspaceOutput = z.infer<
  typeof searchWorkspaceSchema.output
>;
export type GetWorkspaceInput = z.infer<typeof getWorkspaceSchema.input>;
export type GetWorkspaceOutput = z.infer<typeof getWorkspaceSchema.output>;
export type ListWorkspaceMembersInput = z.infer<
  typeof listWorkspaceMembersSchema.input
>;
export type ListWorkspaceMembersOutput = z.infer<
  typeof listWorkspaceMembersSchema.output
>;
export type ListAssistantsInput = z.infer<typeof listAssistantsSchema.input>;
export type ListAssistantsOutput = z.infer<typeof listAssistantsSchema.output>;
export type ListSchedulesInput = z.infer<typeof listSchedulesSchema.input>;
export type ListSchedulesOutput = z.infer<typeof listSchedulesSchema.output>;
export type CreateScheduleInput = z.infer<typeof createScheduleSchema.input>;
export type CreateScheduleOutput = z.infer<typeof createScheduleSchema.output>;
export type UpdateScheduleInput = z.infer<typeof updateScheduleSchema.input>;
export type UpdateScheduleOutput = z.infer<typeof updateScheduleSchema.output>;
export type DeleteScheduleInput = z.infer<typeof deleteScheduleSchema.input>;
export type DeleteScheduleOutput = z.infer<typeof deleteScheduleSchema.output>;

// ============================================================================
// All Schemas (for allSchemas merge in main schemas.ts)
// ============================================================================

export const allSchemasWorkspace = [
  listThreadsSchema,
  getThreadSchema,
  sendChatMessageSchema,
  searchWorkspaceSchema,
  getWorkspaceSchema,
  listWorkspaceMembersSchema,
  listAssistantsSchema,
  listSchedulesSchema,
  createScheduleSchema,
  updateScheduleSchema,
  deleteScheduleSchema,
];
