/**
 * Clay Library
 *
 * Browser-executable Clay.com people and company search operations via internal APIs.
 * Requires user to be logged into Clay at app.clay.com.
 *
 * ⚠️ CRITICAL: CREDIT AWARENESS ⚠️
 * Many Clay operations consume user credits which cost real money.
 * ALWAYS check credit balance via getSubscription() and get explicit user consent
 * before running ANY credit-costing operations. Violating this can cause unexpected charges.
 */

// Re-export all types from schemas
export type {
  ClayUser,
  ClayWorkspace,
  CreditBalances,
  Subscription,
  Person,
  Company,
  PeopleSearchFilters,
  CompanySearchFilters,
  SavedSearch,
  GetContextInput,
  GetContextOutput,
  GetWorkspacesInput,
  GetWorkspacesOutput,
  GetSubscriptionInput,
  GetSubscriptionOutput,
  SearchPeopleInput,
  SearchPeopleOutput,
  SearchCompaniesInput,
  SearchCompaniesOutput,
  GetRelatedKeywordsInput,
  GetRelatedKeywordsOutput,
  GetSavedSearchesInput,
  GetSavedSearchesOutput,
  GetPeopleSearchLimitInput,
  GetPeopleSearchLimitOutput,
  CreateSavedSearchInput,
  CreateSavedSearchOutput,
  DeleteSavedSearchInput,
  DeleteSavedSearchOutput,
  ClayWorkbook,
  ClayField,
  ClayTable,
  ClayRecord,
  ListWorkbooksInput,
  ListWorkbooksOutput,
  ListTablesInput,
  ListTablesOutput,
  GetTableInput,
  GetTableOutput,
  GetTableRecordsInput,
  GetTableRecordsOutput,
  CreateTableInput,
  CreateTableOutput,
  CreateWorkbookInput,
  CreateWorkbookOutput,
  DeleteTableInput,
  DeleteTableOutput,
  DeleteWorkbookInput,
  DeleteWorkbookOutput,
  DeleteRecordsInput,
  DeleteRecordsOutput,
  ListRecordIdsInput,
  ListRecordIdsOutput,
  GetTableRowCountInput,
  GetTableRowCountOutput,
  DeleteAllRecordsInput,
  DeleteAllRecordsOutput,
  RunEnrichmentColumnInput,
  RunEnrichmentColumnOutput,
  CreateWaterfallEnrichmentInput,
  CreateWaterfallEnrichmentOutput,
  CreatePeopleTableInput,
  CreatePeopleTableOutput,
  CreateCompanyTableInput,
  CreateCompanyTableOutput,
  SendToTableInput,
  SendToTableOutput,
  ClayFolder,
  CreateFolderInput,
  CreateFolderOutput,
  DeleteFolderInput,
  DeleteFolderOutput,
  ClayResource,
  SearchResourcesInput,
  SearchResourcesOutput,
  ClaySource,
  ListSourcesInput,
  ListSourcesOutput,
  DeleteSourceInput,
  DeleteSourceOutput,
  RenameTableInput,
  RenameTableOutput,
  RenameWorkbookInput,
  RenameWorkbookOutput,
  MoveToFolderInput,
  MoveToFolderOutput,
  ListFoldersInput,
  ListFoldersOutput,
  RenameFolderInput,
  RenameFolderOutput,
  UpdateRecordsInput,
  UpdateRecordsOutput,
  ListViewsInput,
  ListViewsOutput,
  CreateFieldInput,
  CreateFieldOutput,
  UpdateFieldInput,
  UpdateFieldOutput,
  DeleteFieldInput,
  DeleteFieldOutput,
  CreateViewInput,
  CreateViewOutput,
  UpdateViewInput,
  UpdateViewOutput,
  DeleteViewInput,
  DeleteViewOutput,
  DuplicateTableInput,
  DuplicateTableOutput,
  ExportTableInput,
  ExportTableOutput,
  ListCampaignsInput,
  ListCampaignsOutput,
  ListWorkspaceMembersInput,
  ListWorkspaceMembersOutput,
  ListSignalsInput,
  ListSignalsOutput,
  GetSignalInput,
  GetSignalOutput,
  UpdateSignalInput,
  UpdateSignalOutput,
  CreateSignalInput,
  CreateSignalOutput,
  DeleteSignalInput,
  DeleteSignalOutput,
  ListClaygentsInput,
  ListClaygentsOutput,
  GetClaygentInput,
  GetClaygentOutput,
  CreateClaygentInput,
  CreateClaygentOutput,
  UpdateClaygentInput,
  UpdateClaygentOutput,
  DeleteClaygentInput,
  DeleteClaygentOutput,
  RunClaygentInput,
  RunClaygentOutput,
  GetClaygentRunInput,
  GetClaygentRunOutput,
  ListAppAccountsInput,
  ListAppAccountsOutput,
  SetDefaultAppAccountInput,
  SetDefaultAppAccountOutput,
  GetWorkspaceDetailsInput,
  GetWorkspaceDetailsOutput,
  ListWorkbookTablesInput,
  ListWorkbookTablesOutput,
  ListWorkspaceTablesInput,
  ListWorkspaceTablesOutput,
  ListClaygentDocumentsInput,
  ListClaygentDocumentsOutput,
  CreateClaygentDocumentInput,
  CreateClaygentDocumentOutput,
  DeleteClaygentDocumentInput,
  DeleteClaygentDocumentOutput,
  AddClaygentColumnInput,
  AddClaygentColumnOutput,
  CreateCampaignInput,
  CreateCampaignOutput,
  DeleteCampaignInput,
  DeleteCampaignOutput,
  GetCampaignSettingsInput,
  GetCampaignSettingsOutput,
  UpdateCampaignSettingsInput,
  UpdateCampaignSettingsOutput,
  UpdateCampaignStatusInput,
  UpdateCampaignStatusOutput,
  ListSequencerEmailAccountsInput,
  ListSequencerEmailAccountsOutput,
  ListGlobalBlocklistInput,
  ListGlobalBlocklistOutput,
  AddToGlobalBlocklistInput,
  AddToGlobalBlocklistOutput,
  RemoveFromGlobalBlocklistInput,
  RemoveFromGlobalBlocklistOutput,
  GetEmailAccountConnectUrlInput,
  GetEmailAccountConnectUrlOutput,
  AddCampaignEmailAccountsInput,
  AddCampaignEmailAccountsOutput,
  RemoveCampaignEmailAccountsInput,
  RemoveCampaignEmailAccountsOutput,
  ListCampaignWebhooksInput,
  ListCampaignWebhooksOutput,
  CreateCampaignWebhookInput,
  CreateCampaignWebhookOutput,
  SetCampaignSequenceInput,
  SetCampaignSequenceOutput,
  GetCampaignSequenceInput,
  GetCampaignSequenceOutput,
  SetCampaignScheduleInput,
  SetCampaignScheduleOutput,
  SetCampaignLeadEmailInput,
  SetCampaignLeadEmailOutput,
  GetCampaignScheduleInput,
  GetCampaignScheduleOutput,
  SendTestEmailInput,
  SendTestEmailOutput,
  GetCreditReportInput,
  GetCreditReportOutput,
  GetGlobalCampaignStatsInput,
  GetGlobalCampaignStatsOutput,
  InviteWorkspaceMemberInput,
  InviteWorkspaceMemberOutput,
  RemoveWorkspaceMemberInput,
  RemoveWorkspaceMemberOutput,
  UpdateWorkspaceMemberRoleInput,
  UpdateWorkspaceMemberRoleOutput,
  CreateWebhookSourceInput,
  CreateWebhookSourceOutput,
  CreateGoogleSheetsSourceInput,
  CreateGoogleSheetsSourceOutput,
  CreateCrmImportSourceInput,
  CreateCrmImportSourceOutput,
  CreateActionSourceInput,
  CreateActionSourceOutput,
  GetActionInputsInput,
  GetActionInputsOutput,
  GetDynamicFieldOptionsInput,
  GetDynamicFieldOptionsOutput,
  CreateSalesNavSourceInput,
  CreateSalesNavSourceOutput,
  DeleteCampaignWebhookInput,
  DeleteCampaignWebhookOutput,
  ListInboxRepliesInput,
  ListInboxRepliesOutput,
  SendInboxReplyInput,
  SendInboxReplyOutput,
  SetLeadCategoryInput,
  SetLeadCategoryOutput,
  SetLeadReadStatusInput,
  SetLeadReadStatusOutput,
  ListCampaignEmailAccountsInput,
  ListCampaignEmailAccountsOutput,
  GetMessageHistoryInput,
  GetMessageHistoryOutput,
  ListTrashInput,
  ListTrashOutput,
  RestoreResourceInput,
  RestoreResourceOutput,
  UpdateWorkspaceInput,
  UpdateWorkspaceOutput,
  GetResourceInput,
  GetResourceOutput,
  LogResourceActivityInput,
  LogResourceActivityOutput,
  RemoveWorkspaceUserInput,
  RemoveWorkspaceUserOutput,
  GetKnockTokenInput,
  GetKnockTokenOutput,
  GetCreditAccrualInput,
  GetCreditAccrualOutput,
  GetWorkbookInput,
  GetWorkbookOutput,
  GetWorkbookOverviewInput,
  GetWorkbookOverviewOutput,
  ListSubroutinesInput,
  ListSubroutinesOutput,
  DuplicateViewInput,
  DuplicateViewOutput,
  StopFieldInput,
  StopFieldOutput,
  GetFieldRunStatusInput,
  GetFieldRunStatusOutput,
  GetFieldsRunStatusInput,
  GetFieldsRunStatusOutput,
  SetFieldRunConditionInput,
  SetFieldRunConditionOutput,
  GetSourceRunsInput,
  GetSourceRunsOutput,
  TriggerSourceSyncInput,
  TriggerSourceSyncOutput,
  CreateSourceFromSearchInput,
  CreateSourceFromSearchOutput,
  CustomSignalSourceType,
  ListCustomSignalSourceTypesInput,
  ListCustomSignalSourceTypesOutput,
  CreateCustomSignalInput,
  CreateCustomSignalOutput,
  GetCampaign30dAnalyticsInput,
  GetCampaign30dAnalyticsOutput,
  GetSmartleadAccountInput,
  GetSmartleadAccountOutput,
  GetAppAccountTypesInput,
  GetAppAccountTypesOutput,
  GetAppAccountTypeInput,
  GetAppAccountTypeOutput,
  GetAppAccountsByTypeInput,
  GetAppAccountsByTypeOutput,
  CreateAppAccountInput,
  CreateAppAccountOutput,
  UpdateAppAccountInput,
  UpdateAppAccountOutput,
  DeleteAppAccountInput,
  DeleteAppAccountOutput,
  ListActiveExportsInput,
  ListActiveExportsOutput,
  CreateExportInput,
  CreateExportOutput,
  DownloadCSVInput,
  DownloadCSVOutput,
  ImportCSVInput,
  ImportCSVOutput,
  PermanentDeleteTrashItemInput,
  PermanentDeleteTrashItemOutput,
  BulkPermanentDeleteTrashInput,
  BulkPermanentDeleteTrashOutput,
  SearchEnrichmentsInput,
  SearchEnrichmentsOutput,
  ListSequencerIntegrationsInput,
  ListSequencerIntegrationsOutput,
  GetSequencerDynamicFieldsInput,
  GetSequencerDynamicFieldsOutput,
  AddExportToSequencerInput,
  AddExportToSequencerOutput,
  GenerateClaygentPromptInput,
  GenerateClaygentPromptOutput,
  GenerateOutputSchemaInput,
  GenerateOutputSchemaOutput,
  GenerateFormulaInput,
  GenerateFormulaOutput,
  GetIndustriesInput,
  GetIndustriesOutput,
  GetCountriesInput,
  GetCountriesOutput,
  GetCitiesInput,
  GetCitiesOutput,
  GetStatesInput,
  GetStatesOutput,
  GetFilterOptionsInput,
  GetFilterOptionsOutput,
} from './schemas';

// Context operations
export { getContext } from './context';

// Workspace operations
export {
  getWorkspaces,
  getWorkspaceDetails,
  getSubscription,
  getCreditReport,
  listWorkspaceMembers,
  inviteWorkspaceMember,
  removeWorkspaceMember,
  updateWorkspaceMemberRole,
  listAppAccounts,
  setDefaultAppAccount,
  updateWorkspace,
  getResource,
  logResourceActivity,
  removeWorkspaceUser,
  getKnockToken,
  getCreditAccrual,
} from './workspaces';

// Search operations
export {
  searchPeople,
  searchCompanies,
  getRelatedKeywords,
  getSavedSearches,
  createSavedSearch,
  updateSavedSearch,
  deleteSavedSearch,
  getPeopleSearchLimit,
} from './search';

// Table operations
export {
  listTables,
  getTable,
  createTable,
  renameTable,
  duplicateTable,
  exportTable,
  deleteTable,
  listWorkspaceTables,
  listWorkbookTables,
  listSubroutines,
  sendToTable,
} from './tables';

// Record operations
export {
  getTableRecords,
  createRecords,
  updateRecords,
  deleteRecords,
  listRecordIds,
  getTableRowCount,
  deleteAllRecords,
} from './records';

// Field operations
export {
  createField,
  updateField,
  deleteField,
  stopField,
  getFieldRunStatus,
  getFieldsRunStatus,
  setFieldRunCondition,
} from './fields';

// View operations
export {
  listViews,
  createView,
  updateView,
  setViewFilter,
  setViewSort,
  deleteView,
  duplicateView,
} from './views';

// Workbook operations
export {
  listWorkbooks,
  createWorkbook,
  deleteWorkbook,
  renameWorkbook,
  getWorkbook,
  getWorkbookOverview,
} from './workbooks';

// Folder operations
export {
  createFolder,
  deleteFolder,
  renameFolder,
  listFolders,
  moveToFolder,
  searchResources,
  listTrash,
  restoreResource,
  permanentDeleteTrashItem,
  bulkPermanentDeleteTrash,
} from './folders';

// Source operations
export {
  listSources,
  deleteSource,
  createWebhookSource,
  createGoogleSheetsSource,
  createCrmImportSource,
  createActionSource,
  createSalesNavSource,
  getSourceRuns,
  triggerSourceSync,
  createSourceFromSearch,
  addPeopleSearchToTable,
} from './sources';

// Enrichment operations
export {
  runEnrichmentColumn,
  createWaterfallEnrichment,
  createPeopleTable,
  createCompanyTable,
  addCompanySearchToTable,
  searchEnrichments,
  getActionInputs,
  getDynamicFieldOptions,
  addEnrichmentColumn,
} from './enrichment';

// Campaign operations
export {
  listCampaigns,
  createCampaign,
  deleteCampaign,
  getCampaignSettings,
  updateCampaignSettings,
  updateCampaignStatus,
  setCampaignSchedule,
  getCampaignSchedule,
  sendTestEmail,
  listSequencerEmailAccounts,
  getEmailAccountConnectUrl,
  addCampaignEmailAccounts,
  addLeadsToCampaign,
  removeCampaignEmailAccounts,
  listCampaignEmailAccounts,
  listCampaignWebhooks,
  createCampaignWebhook,
  deleteCampaignWebhook,
  setCampaignSequence,
  getCampaignSequence,
  getCampaignAnalytics,
  getDayWiseAnalytics,
  getGlobalCampaignStats,
  setCampaignLeadEmail,
  getCampaign30dAnalytics,
  getSmartleadAccount,
} from './campaigns';

// Inbox operations
export {
  listInboxReplies,
  sendInboxReply,
  setLeadCategory,
  setLeadReadStatus,
  getMessageHistory,
  listGlobalBlocklist,
  addToGlobalBlocklist,
  batchAddToGlobalBlocklist,
  removeFromGlobalBlocklist,
} from './inbox';

// Integration operations
export {
  getAppAccountTypes,
  getAppAccountType,
  getAppAccountsByType,
  createAppAccount,
  updateAppAccount,
  deleteAppAccount,
} from './integrations';

// Export operations
export {
  listActiveExports,
  createExport,
  downloadCSV,
  importCSV,
  listSequencerIntegrations,
  getSequencerDynamicFields,
  addExportToSequencer,
} from './exports';

// Claygent operations
export {
  listClaygents,
  getClaygent,
  createClaygent,
  updateClaygent,
  deleteClaygent,
  runClaygent,
  getClaygentRun,
  listSignals,
  getSignal,
  createSignal,
  updateSignal,
  deleteSignal,
  listClaygentDocuments,
  listCustomSignalSourceTypes,
  createCustomSignal,
  createClaygentDocument,
  deleteClaygentDocument,
  addClaygentColumn,
} from './claygents';

// AI Generation operations
export {
  generateClaygentPrompt,
  generateOutputSchema,
  generateFormula,
} from './ai-generation';

// Filter option extraction
export {
  getIndustries,
  getCountries,
  getCities,
  getStates,
  getFilterOptions,
} from './filters';
