/**
 * Apollo Library
 *
 * Browser-executable Apollo.io operations via internal APIs.
 * Requires user to be logged into Apollo at app.apollo.io.
 */

export type {
  ModeType,
  ModalityType,
  Pagination,
  Person,
  Company,
  Label,
  FinderView,
  LinkedInData,
  UnlockedContact,
  PhoneNumber,
  ContactEmail,
  Sequence,
  SequenceStep,
  EmailTemplate,
  EmailTemplateFolder,
  Deal,
  DealStage,
  DealPipeline,
  Task,
  Note,
  ContactStage,
  AccountStage,
  Field,
  FieldGroup,
  User,
  EmailAccount,
  SequenceSchedule,
  FacetOption,
  FacetGroup,
  FilterField,
  GetContextInput,
  SearchPeopleInput,
  SelectPeopleInput,
  CreateListInput,
  AddContactsToListInput,
  AddCompaniesToListInput,
  ViewListsInput,
  SearchCompaniesInput,
  SelectCompaniesInput,
  ViewCompanyInput,
  FreeExportPeopleSearchInput,
  ExportPeopleSearchInput,
  ImportCsvToListInput,
  ExportContactsToCsvInput,
  GetSavedSearchesInput,
  CreateSavedSearchInput,
  UpdateSavedSearchInput,
  UnlockEmailInput,
  UnlockPhoneInput,
  SearchSequencesInput,
  ViewSequenceInput,
  CreateSequenceInput,
  UpdateSequenceInput,
  DeleteSequenceInput,
  AddSequenceStepInput,
  EnableSequenceStepInput,
  DisableSequenceStepInput,
  DeleteSequenceStepInput,
  UpdateSequenceStepInput,
  DuplicateSequenceStepInput,
  AddContactsToSequenceInput,
  AddListToSequenceInput,
  ResetFinishedContactsInput,
  GetSequenceContactsInput,
  UpdateSequenceContactStatusInput,
  CloneSequenceInput,
  ListSequenceSchedulesInput,
  CreateSequenceScheduleInput,
  UpdateSequenceScheduleInput,
  DeleteSequenceScheduleInput,
  ActivateSequenceInput,
  DeactivateSequenceInput,
  SearchEmailsInput,
  ViewEmailInput,
  GetEmailAnalyticsInput,
  SendEmailNowInput,
  CreateEmailInput,
  SendEmailInput,
  SearchEmailTemplatesInput,
  CreateEmailTemplateInput,
  UpdateEmailTemplateInput,
  DeleteEmailTemplateInput,
  SearchDealsInput,
  ViewDealInput,
  CreateDealInput,
  UpdateDealInput,
  DeleteDealInput,
  ListDealStagesInput,
  ListDealPipelinesInput,
  SearchTasksInput,
  CreateTaskInput,
  UpdateTaskInput,
  CompleteTaskInput,
  CreateNoteInput,
  UpdateNoteInput,
  DeleteNoteInput,
  CreateContactInput,
  UpdateContactInput,
  DeleteContactInput,
  UpdateContactStageInput,
  ListContactStagesInput,
  CreateAccountInput,
  UpdateAccountInput,
  DeleteAccountInput,
  UpdateAccountStageInput,
  ListAccountStagesInput,
  ListFieldsInput,
  ListUsersInput,
  ListEmailAccountsInput,
  UpdateEmailAccountInput,
  UpdateListInput,
  DeleteListInput,
  RemoveContactsFromListInput,
  RemoveCompaniesFromListInput,
  GetContactsInListInput,
  GetAccountsInListInput,
  GetFilterOptionsInput,
  GetFilterFieldsInput,
  SearchFilterTagsInput,
  GetPlanDetailsInput,
  GetContextOutput,
  SearchPeopleOutput,
  SelectPeopleOutput,
  CreateListOutput,
  AddContactsToListOutput,
  AddCompaniesToListOutput,
  ViewListsOutput,
  SearchCompaniesOutput,
  SelectCompaniesOutput,
  ViewCompanyOutput,
  FreeExportPeopleSearchOutput,
  ExportPeopleSearchOutput,
  ImportCsvToListOutput,
  ExportContactsToCsvOutput,
  GetSavedSearchesOutput,
  CreateSavedSearchOutput,
  UpdateSavedSearchOutput,
  UnlockEmailOutput,
  UnlockPhoneOutput,
  SearchSequencesOutput,
  ViewSequenceOutput,
  CreateSequenceOutput,
  UpdateSequenceOutput,
  DeleteSequenceOutput,
  AddSequenceStepOutput,
  EnableSequenceStepOutput,
  DisableSequenceStepOutput,
  DeleteSequenceStepOutput,
  UpdateSequenceStepOutput,
  DuplicateSequenceStepOutput,
  AddContactsToSequenceOutput,
  AddListToSequenceOutput,
  ResetFinishedContactsOutput,
  GetSequenceContactsOutput,
  UpdateSequenceContactStatusOutput,
  CloneSequenceOutput,
  ListSequenceSchedulesOutput,
  CreateSequenceScheduleOutput,
  UpdateSequenceScheduleOutput,
  DeleteSequenceScheduleOutput,
  ActivateSequenceOutput,
  DeactivateSequenceOutput,
  SearchEmailsOutput,
  ViewEmailOutput,
  GetEmailAnalyticsOutput,
  SendEmailNowOutput,
  CreateEmailOutput,
  SendEmailOutput,
  SearchEmailTemplatesOutput,
  CreateEmailTemplateOutput,
  UpdateEmailTemplateOutput,
  DeleteEmailTemplateOutput,
  ListTemplateVariablesOutput,
  SearchDealsOutput,
  ViewDealOutput,
  CreateDealOutput,
  UpdateDealOutput,
  DeleteDealOutput,
  ListDealStagesOutput,
  ListDealPipelinesOutput,
  SearchTasksOutput,
  CreateTaskOutput,
  UpdateTaskOutput,
  CompleteTaskOutput,
  CreateNoteOutput,
  UpdateNoteOutput,
  DeleteNoteOutput,
  CreateContactOutput,
  UpdateContactOutput,
  DeleteContactOutput,
  UpdateContactStageOutput,
  ListContactStagesOutput,
  CreateAccountOutput,
  UpdateAccountOutput,
  DeleteAccountOutput,
  UpdateAccountStageOutput,
  ListAccountStagesOutput,
  ListFieldsOutput,
  ListUsersOutput,
  ListEmailAccountsOutput,
  UpdateEmailAccountOutput,
  UpdateListOutput,
  DeleteListOutput,
  RemoveContactsFromListOutput,
  RemoveCompaniesFromListOutput,
  GetContactsInListOutput,
  GetAccountsInListOutput,
  GetFilterOptionsOutput,
  GetFilterFieldsOutput,
  SearchFilterTagsOutput,
  GetPlanDetailsOutput,
} from './schemas';

// Context operations
export { getContext } from './context';

// Search operations
export {
  searchPeople,
  searchCompanies,
  viewCompany,
  selectPeople,
  selectCompanies,
} from './search';

// Contact operations
export {
  createContact,
  updateContact,
  deleteContact,
  updateContactStage,
  listContactStages,
  resetFinishedContacts,
} from './contacts';

// Company operations
export {
  createAccount,
  updateAccount,
  deleteAccount,
  updateAccountStage,
  listAccountStages,
} from './companies';

// List operations
export {
  createList,
  viewLists,
  updateList,
  addContactsToList,
  addCompaniesToList,
  deleteList,
  removeContactsFromList,
  removeCompaniesFromList,
  getContactsInList,
  getAccountsInList,
} from './lists';

// Sequence operations
export {
  searchSequences,
  viewSequence,
  createSequence,
  updateSequence,
  deleteSequence,
  unarchiveSequence,
  addSequenceStep,
  enableSequenceStep,
  disableSequenceStep,
  deleteSequenceStep,
  updateSequenceStep,
  duplicateSequenceStep,
  addContactsToSequence,
  addListToSequence,
  getSequenceContacts,
  updateSequenceContactStatus,
  cloneSequence,
  listSequenceSchedules,
  createSequenceSchedule,
  updateSequenceSchedule,
  deleteSequenceSchedule,
  activateSequence,
  deactivateSequence,
} from './sequences';

// Email operations
export {
  searchEmails,
  viewEmail,
  getEmailAnalytics,
  sendEmailNow,
  createEmail,
  sendEmail,
  listTemplateVariables,
} from './emails';

// Email template operations
export {
  searchEmailTemplates,
  createEmailTemplate,
  updateEmailTemplate,
  deleteEmailTemplate,
} from './templates';

// Admin operations
export {
  listFields,
  listUsers,
  listEmailAccounts,
  updateEmailAccount,
} from './admin';

// Export operations
export {
  freeExportPeopleSearch,
  exportPeopleSearch,
  exportContactsToCsv,
  listExports,
} from './exports';

// Import operations
export { importCsvToList } from './imports';

// Deal operations
export {
  searchDeals,
  viewDeal,
  createDeal,
  updateDeal,
  deleteDeal,
  listDealStages,
  listDealPipelines,
} from './deals';

// Task operations
export { searchTasks, createTask, updateTask, completeTask } from './tasks';

// Note operations
export { createNote, updateNote, deleteNote } from './notes';

// Discovery operations
export {
  getSavedSearches,
  createSavedSearch,
  updateSavedSearch,
  unlockEmail,
  unlockPhone,
  getFilterOptions,
  getFilterFields,
  searchFilterTags,
  getPlanDetails,
} from './discovery';

// Call operations
export { searchCalls, getCall, downloadRecording } from './calls';
