import test from "node:test";
import assert from "node:assert/strict";
import { OracleSchema, CommandEventSchema, CdpConnectionSchema, FrictionEventSchema, RunRecordSchema, ReferenceRouteSchema } from "./schema.mjs";

const now = "2026-01-01T00:00:00.000Z";
const oracle = { opaqueCaseId: "r7-atlas", caseId: "case-a", fixtureRevision: "a.1", vagueSymptom: "It changed.", plantedCondition: "private", requiredDiagnosisFacts: [{ id: "cause", fact: "one", why: "why" }], requiredEvidence: [{ id: "proof", evidence: "one", why: "why" }], plausibleWrongAnswer: "other", ranges: { faulty: [{ name: "latency", min: 1, max: 2 }], healthy: [{ name: "latency", min: 0, max: 1 }] }, intendedCapability: "operation", intendedCapabilityMatchers: [["page", "mock"]], escapeHatchMatchers: [["cdp"]], environment: { chromeBuild: "143", flags: [], coldCache: true, repetitions: 1 }, budgets: { calls: 40, minutes: 25, stdoutTokens: 40000 } };
const command = { runId: "run", ordinal: 1, argv: ["-h"], startedAt: now, endedAt: now, elapsedMs: 0, exitCode: 0, signal: null, stdoutBytes: 1, stderrBytes: 0, stdoutTokens: 1, stderrTokens: 0, artifactPaths: [], cwd: "/tmp", pid: 1 };
const cdp = { connId: 1, acceptedAt: now, closedAt: now, remoteAddr: "127.0.0.1", remotePort: 3, bytesToBrowser: 1, bytesToClient: 1, firstRequestLine: "GET /json/list HTTP/1.1" };
const friction = { eventId: "f", runId: "run", commandOrdinals: [1], phase: "discovery", category: "ambiguous-help", expected: "x", actual: "y", workaround: "z", cost: { extraCalls: 0, elapsedMs: 0, stdoutTokens: 0, abandonedArtifacts: [] }, severity: "cosmetic", repetitionKey: "ambiguous-help:root" };
const reference = { caseId: "case-a", measuredAt: now, provisional: false, captureBuildHash: "hash", chromeBuild: "143", hostClass: "host", route: [{ ordinal: 1, argv: ["-h"], elapsedMs: 0, stdoutTokens: 1 }], totals: { calls: 1, elapsedSeconds: 0, stdoutTokens: 1 }, notes: "verified" };
const run = { provenance: { runId: "run", captureBuildHash: "hash", fixtureRevision: "a.1", promptRevision: "v1", chromeBuild: "143", model: "model", hostClass: "host", startedAt: now, browserFlags: [] }, outcome: { reproduced: true, diagnosis: "cause", confidence: "high", stopReason: "established" }, evidence: [{ claim: "fact", ordinals: [1], artifactPaths: [] }], hypothesisLedger: [{ hypothesis: "cause", status: "final", formedAtOrdinal: 1, resolvedAtOrdinal: 1, commandCost: 1 }], fallbackLedger: [], outputVolumeLedger: { commands: [{ ordinal: 1, stdoutBytes: 1, stdoutTokens: 1 }], cumulativeStdoutTokens: 1, largestStdoutTokens: 1, contextImpact: "none" }, routeMetrics: { totalCalls: 1, helpCalls: 1, failedCalls: 0, repeatedCalls: 0, escapeHatchCalls: 0, elapsedSeconds: 0, firstIntendedCapabilityOrdinal: 1, establishmentOrdinal: 1, referenceCalls: 1, callRatio: 1, elapsedRatio: 1, stdoutTokenRatio: 1 }, frictionEvents: [friction], grade: { correctness: true, evidenceComplete: true, firstClassCapability: "used", cdpAccounting: { unaccounted: 0, rule: "window" }, callRatio: 1, elapsedRatio: 1, stdoutTokenRatio: 1, finalClass: "pass", reasons: [] } };

for (const [name, schema, valid] of [["oracle", OracleSchema, oracle], ["command", CommandEventSchema, command], ["cdp", CdpConnectionSchema, cdp], ["friction", FrictionEventSchema, friction], ["run", RunRecordSchema, run], ["reference", ReferenceRouteSchema, reference]]) {
  test(`${name} schema round-trips and rejects malformed data`, () => { assert.deepEqual(schema.parse(valid), valid); assert.throws(() => schema.parse({})); });
}
